version: '3.8'
services:
  mysqllf:
    image: mysql:5.7
    platform: linux/amd64
    env_file: ./.env
    environment:
      - MYSQL_USER=$SQL_USER
      - MYSQL_ROOT_PASSWORD=$SQL_PASSWORD
      - MYSQL_PASSWORD=$SQL_PASSWORD
      - MYSQL_DATABASE=$SQL_DB
    ports:
      - $SQL_PORT:$SQL_PORT
  server:
    depends_on: 
      - mysqllf
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    ports:
      - $PORT:$PORT
    restart: always
